### ISSUE TITLE
please add tag for 1.1.0 release

### ISSUE THREAD

**Issue by pravi** [iarna/wide-align#50]
We like to use github tarballs to build debian packages.

**Comment by iarna** [comment]
I've done that, but... github tarballs are never a canonical source for npm modules. It's fine for _this_ module but not in general. Unless you all just run `npm install && npm pack` as your debian build process, you are pretty much guaranteed to break some modules. But it gets worse! There's now `prepublishOnly` which can ALSO change what's published and only runs on `npm publish`. The tarball on the registry is the only true source of npm modules and I encourage you to use it. If you want to fetch things programmatically, [https://github.com/zkat/pacote](pacote) is specifically designed to do that (and is the heart of npm@5).

**Comment by pravi** [comment]
@iarna npm dist tarballs can contain pre-built binaries (browserified, transpiled, minified), we want to build everything from source within debian. So if package.json specifies a way to build things, we do that (browserify, transpile, minifiy) in our build process. We also make sure all tests are passing (sometimes modules have tests only in github repo, which is also a reason to prefer github tarballs).
